CREATE TABLE STAFF
(
    ID  VARCHAR(128)   PRIMARY KEY ,
    NAME VARCHAR(128)  NOT NULL COMMENT '员工姓名',
    DEPARTMENT VARCHAR(128)  NOT NULL COMMENT '员工部门'
);

CREATE TABLE SALARY
(
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    MATERIAL_ID  VARCHAR(128)  NOT NULL COMMENT '简易编号',
    STAFF_ID VARCHAR(128)  NOT NULL COMMENT '员工ID',
    SALARY_DATE VARCHAR(30)  NOT NULL COMMENT '记录日期',
    START TIMESTAMP NOT NULL COMMENT '开始时间',
    END TIMESTAMP  NOT NULL COMMENT '结束时间',
    LAUNCH_DEDUCT BOOLEAN  NOT NULL DEFAULT FALSE COMMENT '是否用餐',
    QUANTITY INT COMMENT '数量',
    WORK_OVERTIME BOOLEAN  NOT NULL DEFAULT FALSE COMMENT '是否为加班',
    SUBSIDY DECIMAL(16,4) default null COMMENT '补贴',
    SALARY_SUMMARY DECIMAL(16,4) default null  COMMENT '工资',
    WORK_TIME DECIMAL(16,4) default null COMMENT '工作时间',
    UNIQUE KEY INDEX_STAFF_ID_START_END ( `STAFF_ID`,`SALARY_DATE`, `START`, `END` )
);

CREATE TABLE MATERIAL
(
    MATERIAL_ID  VARCHAR(128)  PRIMARY KEY ,
    DRAWING_ID  VARCHAR(128) NOT NULL  COMMENT '图号',
    PROCESSING_ID VARCHAR(128) NOT NULL COMMENT  '工序号',
    PROCESSING_NAME VARCHAR(128) NOT NULL COMMENT '工序',
    UNIT_PRICE DECIMAL(16,4) NOT NULL COMMENT '单价',
    QUOTA DECIMAL(16,4) NOT NULL COMMENT '定额'
);
